//go:build integration

package syncer

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"slices"
	"strconv"
	"sync"
	"testing"
	"time"

	"github.com/docker/go-connections/nat"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
	"kbsync/internal/config"
)

type databaseContainer struct {
	container testcontainers.Container
	dsn       string
}

func TestFullAndIncrementalSync(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 4*time.Minute)
	defer cancel()

	source := startDatabaseContainer(t, ctx)
	target := startDatabaseContainer(t, ctx)
	sourceDB := openTestDatabase(t, ctx, source.dsn)
	targetDB := openTestDatabase(t, ctx, target.dsn)

	execTestSQL(t, ctx, sourceDB, `
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    payload bytea,
    note text,
    updated_at timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX users_name_uidx ON public.users USING btree (name);
INSERT INTO public.users (name, payload, note, updated_at) VALUES
    ('alice', decode('0102', 'hex'), NULL, '2026-09-14T01:00:00Z'),
    ('bob', decode('0304', 'hex'), '', '2026-09-14T02:00:00Z');
CREATE TABLE public.events (
    event_time timestamp with time zone NOT NULL,
    payload text NOT NULL
);
INSERT INTO public.events VALUES
    ('2026-09-14T01:00:00Z', 'a'),
    ('2026-09-14T01:00:00Z', 'b');
CREATE TABLE public.orders (
    tenant_id integer NOT NULL,
    order_id integer NOT NULL,
    status text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (tenant_id, order_id),
    CONSTRAINT orders_user_fk FOREIGN KEY (tenant_id) REFERENCES public.users(id)
);
INSERT INTO public.orders VALUES
    (1, 10, 'new', '2026-09-14T01:00:00Z'),
    (2, 10, 'new', '2026-09-14T01:00:00Z');`)

	cfg := config.Config{
		Source:       config.Database{DSN: source.dsn, MaxOpenConns: 2},
		Target:       config.Database{DSN: target.dsn, MaxOpenConns: 2},
		BatchSize:    100,
		Parallelism:  3,
		MaxParams:    30000,
		MetricsFile:  t.TempDir() + "/kbsync.prom",
		StateFile:    t.TempDir() + "/state.json",
		FullStrategy: "truncate",
		Tables: []config.Table{{
			Source: "public.users", Target: "mirror.users", Cursor: "updated_at", KeyColumns: []string{"id"},
		}, {
			Source: "public.events", Target: "mirror.events", Cursor: "event_time",
		}, {
			Source: "public.orders", Target: "mirror.orders", Cursor: "updated_at", KeyColumns: []string{"tenant_id", "order_id"},
		}},
	}
	runner, err := Open(ctx, cfg, t.Logf)
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}
	t.Cleanup(func() { _ = runner.Close() })
	progress := &recordingProgress{}
	runner.SetProgressReporter(progress)

	if err := runner.Full(ctx); err != nil {
		t.Fatalf("Full() error = %v", err)
	}
	assertRowCount(t, ctx, targetDB, "mirror.users", 2)
	assertString(t, ctx, targetDB, `SELECT name FROM mirror.users WHERE id = 2`, "bob")
	assertCatalogCount(t, ctx, targetDB, `SELECT count(*) FROM mirror.users WHERE id=1 AND note IS NULL`, 1)
	assertCatalogCount(t, ctx, targetDB, `SELECT count(*) FROM mirror.users WHERE id=2 AND note=''`, 1)
	assertCatalogCount(t, ctx, targetDB, `SELECT count(*) FROM pg_indexes WHERE schemaname='mirror' AND tablename='users' AND indexname='users_name_uidx'`, 1)
	assertRowCount(t, ctx, targetDB, "mirror.events", 2)
	assertRowCount(t, ctx, targetDB, "mirror.orders", 2)
	assertCatalogCount(t, ctx, targetDB, `SELECT count(*) FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE con.contype='f' AND con.conname='orders_user_fk' AND n.nspname='mirror' AND c.relname='orders'`, 1)

	execTestSQL(t, ctx, sourceDB, `
ALTER TABLE public.users ADD COLUMN email text NOT NULL DEFAULT '';
UPDATE public.users SET name='alice-updated', email='alice@example.test', updated_at='2026-09-14T03:00:00Z' WHERE id=1;
INSERT INTO public.users (name, email, updated_at) VALUES ('carol', 'carol@example.test', '2026-09-14T04:00:00Z');`)
	execTestSQL(t, ctx, sourceDB, `
DELETE FROM public.events WHERE event_time='2026-09-14T01:00:00Z';
INSERT INTO public.events VALUES
    ('2026-09-14T01:00:00Z', 'a-replaced'),
    ('2026-09-14T02:00:00Z', 'c'),
    ('2026-09-14T02:00:00Z', 'd');
UPDATE public.orders SET status='paid', updated_at='2026-09-14T03:00:00Z' WHERE tenant_id=1 AND order_id=10;
INSERT INTO public.orders VALUES (1, 11, 'new', '2026-09-14T04:00:00Z');`)

	if err := runner.Incremental(ctx); err != nil {
		t.Fatalf("Incremental() error = %v", err)
	}
	assertRowCount(t, ctx, targetDB, "mirror.users", 3)
	assertString(t, ctx, targetDB, `SELECT name || ':' || email FROM mirror.users WHERE id=1`, "alice-updated:alice@example.test")
	assertString(t, ctx, targetDB, `SELECT email FROM mirror.users WHERE id=3`, "carol@example.test")
	assertCatalogCount(t, ctx, targetDB, `SELECT count(*) FROM information_schema.columns WHERE table_schema='mirror' AND table_name='users' AND column_name='email'`, 1)
	assertRowCount(t, ctx, targetDB, "mirror.events", 3)
	assertString(t, ctx, targetDB, `SELECT payload FROM mirror.events WHERE event_time='2026-09-14T01:00:00Z'`, "a-replaced")
	assertRowCount(t, ctx, targetDB, "mirror.orders", 3)
	assertString(t, ctx, targetDB, `SELECT status FROM mirror.orders WHERE tenant_id=1 AND order_id=10`, "paid")

	var nextID int64
	if err := targetDB.QueryRowContext(ctx, `INSERT INTO mirror.users (name, updated_at) VALUES ('dave', '2026-09-14T05:00:00Z') RETURNING id`).Scan(&nextID); err != nil {
		t.Fatalf("verify synchronized sequence: %v", err)
	}
	if nextID != 4 {
		t.Fatalf("next sequence value = %d, want 4", nextID)
	}

	if err := runner.Incremental(ctx); err != nil {
		t.Fatalf("second Incremental() error = %v", err)
	}
	assertRowCount(t, ctx, targetDB, "mirror.users", 4)
	progress.assertCompleted(t, 3, 9)
}

type recordingProgress struct {
	mu       sync.Mutex
	begins   []int
	totals   []int64
	finishes int
	bars     []*recordingTableProgress
}

func (p *recordingProgress) Begin(tableCount int, totalRows int64) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.begins = append(p.begins, tableCount)
	p.totals = append(p.totals, totalRows)
}

func (p *recordingProgress) Start(source, target string, totalRows int64) TableProgress {
	p.mu.Lock()
	defer p.mu.Unlock()
	bar := &recordingTableProgress{source: source, target: target, total: totalRows}
	p.bars = append(p.bars, bar)
	return bar
}

func (p *recordingProgress) Finish() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.finishes++
}

func (p *recordingProgress) assertCompleted(t *testing.T, runs, bars int) {
	t.Helper()
	p.mu.Lock()
	defer p.mu.Unlock()
	if len(p.begins) != runs || p.finishes != runs {
		t.Fatalf("progress runs = begins:%v finishes:%d, want %d", p.begins, p.finishes, runs)
	}
	wantTotals := []int64{6, 9, 0}
	if !slices.Equal(p.totals, wantTotals) {
		t.Fatalf("progress total rows = %v, want %v", p.totals, wantTotals)
	}
	if len(p.bars) != bars {
		t.Fatalf("progress bars = %d, want %d", len(p.bars), bars)
	}
	for _, bar := range p.bars {
		bar.mu.Lock()
		if !bar.completed || bar.aborted || bar.current > bar.total {
			t.Errorf("progress bar %s->%s = current:%d total:%d completed:%v aborted:%v", bar.source, bar.target, bar.current, bar.total, bar.completed, bar.aborted)
		}
		bar.mu.Unlock()
	}
}

type recordingTableProgress struct {
	mu        sync.Mutex
	source    string
	target    string
	total     int64
	current   int64
	completed bool
	aborted   bool
}

func (p *recordingTableProgress) Add(rows int64, _ time.Duration) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.current += rows
}

func (p *recordingTableProgress) Complete() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.completed = true
}

func (p *recordingTableProgress) Abort() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.aborted = true
}

func startDatabaseContainer(t testing.TB, ctx context.Context) databaseContainer {
	t.Helper()
	image := envOrDefault("KBSYNC_TEST_IMAGE", "lihongjie0209/kingbase:latest")
	port := envOrDefault("KBSYNC_TEST_PORT", "54321")
	user := envOrDefault("KBSYNC_TEST_USER", "system")
	password := envOrDefault("KBSYNC_TEST_PASSWORD", "manager")
	database := envOrDefault("KBSYNC_TEST_DATABASE", "test")
	containerPort := nat.Port(port + "/tcp")

	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			Image:        image,
			Privileged:   true,
			ExposedPorts: []string{string(containerPort)},
			Env: map[string]string{
				"POSTGRES_USER": user, "POSTGRES_PASSWORD": password, "POSTGRES_DB": database,
				"KINGBASE_USER": user, "KINGBASE_PASSWORD": password, "KINGBASE_DATABASE": database,
				"DB_USER": user, "DB_PASSWORD": password, "DB_MODE": "pg", "ENABLE_CI": "no",
			},
			WaitingFor: wait.ForListeningPort(containerPort).WithStartupTimeout(2 * time.Minute),
		},
		Started: true,
	})
	if err != nil {
		t.Fatalf("start %s: %v", image, err)
	}
	t.Cleanup(func() {
		terminateCtx, terminateCancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer terminateCancel()
		if err := container.Terminate(terminateCtx); err != nil {
			t.Errorf("terminate container: %v", err)
		}
	})
	host, err := container.Host(ctx)
	if err != nil {
		t.Fatal(err)
	}
	mappedPort, err := container.MappedPort(ctx, containerPort)
	if err != nil {
		t.Fatal(err)
	}
	dsn := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable client_encoding=UTF-8", host, mappedPort.Port(), user, password, database)
	return databaseContainer{container: container, dsn: dsn}
}

func openTestDatabase(t testing.TB, ctx context.Context, dsn string) *sql.DB {
	t.Helper()
	db, err := sql.Open("kingbase", dsn)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = db.Close() })
	deadline := time.Now().Add(time.Minute)
	for {
		if err := db.PingContext(ctx); err == nil {
			return db
		} else if time.Now().After(deadline) {
			t.Fatalf("database did not become ready: %v", err)
		}
		time.Sleep(500 * time.Millisecond)
	}
}

func execTestSQL(t *testing.T, ctx context.Context, db *sql.DB, query string) {
	t.Helper()
	if _, err := db.ExecContext(ctx, query); err != nil {
		t.Fatalf("execute fixture SQL: %v", err)
	}
}

func assertRowCount(t *testing.T, ctx context.Context, db *sql.DB, table string, want int) {
	t.Helper()
	assertCatalogCount(t, ctx, db, "SELECT count(*) FROM "+table, want)
}

func assertCatalogCount(t *testing.T, ctx context.Context, db *sql.DB, query string, want int) {
	t.Helper()
	var got int
	if err := db.QueryRowContext(ctx, query).Scan(&got); err != nil {
		t.Fatal(err)
	}
	if got != want {
		t.Fatalf("count for %q = %d, want %d", query, got, want)
	}
}

func assertString(t *testing.T, ctx context.Context, db *sql.DB, query, want string) {
	t.Helper()
	var got string
	if err := db.QueryRowContext(ctx, query).Scan(&got); err != nil {
		t.Fatal(err)
	}
	if got != want {
		t.Fatalf("value for %q = %q, want %q", query, got, want)
	}
}

func envOrDefault(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}

func TestEnvironmentPortIsNumeric(t *testing.T) {
	if _, err := strconv.Atoi(envOrDefault("KBSYNC_TEST_PORT", "54321")); err != nil {
		t.Fatalf("KBSYNC_TEST_PORT must be numeric: %v", err)
	}
}
